#!/usr/bin/env node
/**
 * The mock data and the recommendation/search logic are plain TypeScript with no
 * DOM dependencies, so the web app and the native app run the exact same code.
 * This copies them across the Metro boundary rather than relying on monorepo
 * resolution, which keeps `expo start` working from a clean checkout.
 *
 * Source of truth: ../src/lib. Never edit mobile/src/lib/shared by hand.
 */
import { copyFileSync, existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const from = join(here, '..', '..', 'src', 'lib')
const to = join(here, '..', 'src', 'lib', 'shared')

const FILES = ['types.ts', 'utils.ts', 'topics.ts', 'posts.ts', 'users.ts', 'social.ts', 'identity.ts', 'recommend.ts', 'search.ts']

if (!existsSync(from)) {
  console.warn('[sync-shared] web app not found alongside mobile/ — using the committed copy')
  process.exit(0)
}

mkdirSync(to, { recursive: true })
for (const file of FILES) {
  const src = join(from, file)
  if (!existsSync(src)) { console.warn(`[sync-shared] missing ${file}`); continue }
  copyFileSync(src, join(to, file))
}

writeFileSync(
  join(to, 'index.ts'),
  `// Generated by scripts/sync-shared.mjs — do not edit.\n` +
    FILES.map((f) => `export * from './${f.replace(/\.ts$/, '')}'`).join('\n') + '\n',
)

const stale = readdirSync(to).filter((f) => !FILES.includes(f) && f !== 'index.ts')
if (stale.length) console.warn(`[sync-shared] stale files in shared/: ${stale.join(', ')}`)

console.log(`[sync-shared] copied ${FILES.length} modules from web`)
